import submenu from './modules/submenu.js';
import sidebar from './modules/sidebar.js';
import darkTheme from './modules/darkTheme.js';
import fullscreen from './modules/fullscreen.js';
import dropdown from './modules/dropdown.js';
import searchHeader from './modules/searchHeader.js';
import notifications from './modules/notifications.js';
import codePreview from './modules/codePreview.js';
import alerts from './modules/alerts.js';
import inputs from './modules/inputs.js';
import cardTabs from './modules/cardTabs.js';
import modal from './modules/modal.js';

submenu();
sidebar();
darkTheme();
fullscreen();
dropdown();
searchHeader();
notifications();
codePreview();
alerts();
inputs();
cardTabs();
modal();
